:sparkles: add working lambda trigger
Signed-off-by: Luke-zhang-04 <luke.zhang2004dev@gmail.com>

diff --git a/hooks/post-signup/deploy b/hooks/post-signup/deploy
--- a/hooks/post-signup/deploy
+++ b/hooks/post-signup/deploy
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-./dockerBuild
+result="$(./dockerBuild)"
+
+if [[ ! "$result" ]]; then
+    echo "An error occured"
+    exit 1
+fi
 
 sudo cp ./build/main ./main
 
